[2025-09-24T09:24:24.371+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_dag.staging_ops.load_data_to_staging scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T09:24:24.383+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_dag.staging_ops.load_data_to_staging scheduled__2025-09-23T00:00:00+00:00 [queued]>
[2025-09-24T09:24:24.384+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-24T09:24:24.406+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging_ops.load_data_to_staging> on 2025-09-23 00:00:00+00:00
[2025-09-24T09:24:24.415+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2025-09-24T09:24:24.420+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'sales_dag', 'staging_ops.load_data_to_staging', 'scheduled__2025-09-23T00:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/sales_dag.py', '--cfg-path', '/tmp/tmps813lw30']
[2025-09-24T09:24:24.424+0000] {standard_task_runner.py:85} INFO - Job 232: Subtask staging_ops.load_data_to_staging
[2025-09-24T09:24:24.465+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-24T09:24:24.574+0000] {task_command.py:415} INFO - Running <TaskInstance: sales_dag.staging_ops.load_data_to_staging scheduled__2025-09-23T00:00:00+00:00 [running]> on host 3517d925e010
[2025-09-24T09:24:24.844+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sales_dag' AIRFLOW_CTX_TASK_ID='staging_ops.load_data_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T00:00:00+00:00'
[2025-09-24T09:24:24.847+0000] {sales_dag.py:126} INFO - Loading data to staging has been started
[2025-09-24T09:24:24.886+0000] {sales_dag.py:131} INFO - CSV path received: None
[2025-09-24T09:24:24.922+0000] {base.py:73} INFO - Using connection ID '***_conn' for task execution.
[2025-09-24T09:24:24.946+0000] {sales_dag.py:151} INFO - Error has happend when loading data into staging table : expected str, bytes or os.PathLike object, not NoneType
[2025-09-24T09:24:24.947+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-09-24T09:24:24.980+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=sales_dag, task_id=staging_ops.load_data_to_staging, execution_date=20250923T000000, start_date=20250924T092424, end_date=20250924T092424
[2025-09-24T09:24:25.035+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-09-24T09:24:25.101+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
